[package]
name = "tb_row"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html


[dependencies]
tb_row_derive = { path = "../tb_row_derive", package = "tb_row_derive" }
